### PR TITLE
Added support for Scala 2.13

### LINKED ISSUE #54: Add support for 2.13
Investigate the necessary changes and apply them. Once they're in place, make sure to reflect them in CircleCI configuration.

### PR DESCRIPTION
**Pull request by tomasherman**
fixes #54

### CODE REVIEW

**Comment by mijicd** [comment]
Release artifact is published. The last thing that needs to be done here is separate the options between 2.13 (e.g. `-Ypartial-unification`) causes compilation issues atm.

**Comment by tomasherman** [comment]
yep, on it - i was at lunch ... actually more changes need to happen but it should be just drone work ;)

**Comment by tomasherman** [comment]
@mijicd so there is bunch of deprecated features in scala 2.13 used in this project - are you ok with turning off fatal warnings?

**Comment by mijicd** [comment]
Well, I'd use that option as the last case. Let's try to solve these issues, and maybe use the silencer otherwise (something similar has been done in core project).

**Comment by tomasherman** [comment]
Yeah. Most of them should be fixable... However the biggest blocker so far
is testz 0.0.5 not being released for 2.13 and 0.0.6 having very different
api :-(

**Comment by mijicd** [comment]
That's been tackled by @mtsokol in #53. Maybe you can pair up and push that one?

**Comment by mtsokol** [comment]
@mijicd give me an hour and I should be done with it

**Comment by tomasherman** [comment]
thats great - i worked for like an hour on migration to testz 0.0.6 and i bailed out :D

**Comment by tomasherman** [comment]
@mtsokol hows it going? is there something i can help with?

**Comment by mtsokol** [comment]
@tomasherman I've just completed it here https://github.com/zio/zio-nio/pull/64. 
But unfortunately we need to wait until tomorrow as the current release does not have crucial features in `zio-test` (support for `Throwable` in `testM`) but it is on master so feel free to run it with local release

**Comment by tomasherman** [comment]
aw that's a shame - either way though these changes should work

**Comment by mijicd** [comment]
#64 is in, looking forward to this one!

**Comment by tomasherman** [comment]
On it

**Comment by tomasherman** [comment]
ready for review and to merge (from my point of view ;))

**Pull request merged**
