### PR TITLE
Add support for java.nio.file package

### PR DESCRIPTION
**Pull request by quelgar**
~**Still very much WIP!**. Quite a lot of stuff still to fix up.~

This is now in decent shape. No tests yet, however.

### CODE REVIEW

**Comment by pshemass** [comment]
@quelgar do you need help with this?

**Comment by pshemass** [comment]
@quelgar it looks like compilation is failing for 2.13 because of ```JavaConverters``` deprecation. Please look into that and let me know if you are able to fix this.

**Comment by quelgar** [comment]
> @quelgar it looks like compilation is failing for 2.13 because of `JavaConverters` deprecation. Please look into that and let me know if you are able to fix this.

Yep. I was planning on fixing it with a simple wrapper with 2.12 and 2.13 variants. I've struggled a bit with the tooling for cross-building. Neither IntelliJ or Metals seem to let you pick a different Scala version, looks like I have to temporarily change `build.sbt` and reload everything.

**Comment by pshemass** [comment]
@mijicd do you know how to handle this?

**Comment by mijicd** [comment]
@pshemass for the quick & dirty fix `silencer` will work (we did something similar in core project for collection issues). I will follow up on the issue over the weekend.

**Comment by quelgar** [comment]
Ok, I've rebased, silenced the `JavaConverters` warnings under 2.13, fixed the mdoc code.

Still haven't written many tests, I'm afraid.

**Comment by pshemass** [comment]
@quelgar could you list here tests that you want to add I can write some?

**Comment by mijicd** [comment]
Even better, we can tackle them during the upcoming hackathon.

**Comment by quelgar** [comment]
It would be great to have tests for the more complex stuff, like the directory listing/walking stuff in `zio.nio.file.Files` that returns `ZStream`. The attribute stuff in that class is also a little involved.

Probably better to do hackathon work on a new branch, so I'd vote we merge this one now.

**Comment by mijicd** [comment]
Let's merge it then, but, if possible, could you open the test issues and add them to the hackathon board?

**Comment by quelgar** [comment]
Done, issue #100

**Pull request merged**
