### PR TITLE
fix typo in FileChannel: postion => position

### PR DESCRIPTION
**Pull request by domsj**
fyi @jczuchnowski the typo gets duplicated in your PR https://github.com/zio/zio-nio/pull/122

### CODE REVIEW

**Comment by domsj** [comment]
hmm, while I'm here: any reason E = Exception instead of IOException for this method?

**Comment by quelgar** [comment]
We've tended to be pretty conservative with the error type until now. This method is documented as potentially throwing `IllegalArgumentException`, so we're reporting via the error type. However, illegal argument would only happen due to a defect, and I've started coming around to the idea that we should tighten the error types to legit failures that callers should deal with, and just die for the defect exceptions. If we make this the policy, there's actually quite a number of methods which would need similar changes.

**Comment by jczuchnowski** [comment]
@quelgar also sometimes by tightening the input type we should be able to get rid of these random runtime exceptions and cleanup the Error type of ZIO.

**Comment by jczuchnowski** [comment]
Anyway, I'm merging it, and will apply the fix in my PR.

**Pull request merged**
