### PR TITLE
Migration to zio-test

### PR DESCRIPTION
**Pull request by mtsokol**
Removed `scalaz-test` and `scalacheck` dependencies and moved to `zio-test`.

We need to wait for next `zio` release because it needs recent master changes.

Also I will also refactor it visually in few places for consistency but it's completed right now.
@mijicd Could you do a review?

### CODE REVIEW

**Comment by tomasherman** [comment]
so apparently new version of zio with test changes was released - is it possible to update this PR and merge it? is there something i can do to help?

**Comment by mijicd** [comment]
@tomasherman they're published seconds ago, it takes some time to propagate :). I think @mtsokol is on it anyhow.

**Comment by mtsokol** [comment]
Yes, I'm constantly checking when it will be available via sbt and will commit final version. Also still doing some minor enhancements for PR.

**Comment by tomasherman** [comment]
🎉

**Comment by mtsokol** [comment]
@mijicd so it is completed, all passing and ready for a brief review once again.

**Pull request merged**
