### PR TITLE
[WIP] Suppressed confusing output. Printing tests' labels

### PR DESCRIPTION
**Pull request by mtsokol**
Hi, I think that current standard test output is really misleading as it's just some fiber's `NullPointerExceptions` and no info about ran tests.

It was first mentioned here #7.

So right now tests that were successful are not printed at all, according to `runner.printTest` that is used. Also, as `Platform.default` from `DefaultRuntime` is used, each `Cause` is unpurely printed in: 
```scala
def reportFailure(cause: Cause[_]): Unit =
        if (!cause.interrupted)
          System.err.println(cause.prettyPrint)
```

### Draft solution

In PR all tests that are run have their status with descriptions printed. Also a custom rough `Platform` is added to avoid printing these unpure stack-traces from fibers. 

I'm not proud of PR yet, it's WIP, I would like discus it first.

What do you think?

### CODE REVIEW

**Comment by quelgar** [comment]
This looks like a good start. I think it's risky to globally filter out all NPEs though, since it could make finding genuine bugs more difficult. We could introduce our own `TestRuntimeException` that we'll only throw in tests where we want to test error handling (instead of using NPE). This exception could then be safely ignored in `reportFailure`.

**Comment by mtsokol** [comment]
@quelgar I've looked again at it and right now I don't see a possibility to replace thrown NPE with custom test exceptions. These are thrown internally and here I have no way substituting them I guess, but I heard that it's a pain in other zio ecosystem projects so it might be solved in core?
 
But going back to this PR, I think that printing test labels is ok, but right now I'm not sure if NPE filtering can be done other way.
@mijicd what do you think about it?

**Comment by pshemass** [comment]
we should migrate those test to ```zio-test```

**Comment by mijicd** [comment]
Let's use the hackathon and move to zio tests. From that point we can fiddle in any direction we want.

**Comment by mtsokol** [comment]
Great, I see that there are already examples by @ghostdogpr in core zio so if nobody already started it I will start it right now.

**Comment by mijicd** [comment]
Is it completely superseded by #64 ? If so, I propose to close it.

**Comment by mtsokol** [comment]
@mijicd yes, it is. Closing.

**Pull request closed without merging**
